import { LevelData } from '../../../src/types/level';


export const levelData: LevelData = {
	waves: [
		{ postDelay: 120, reward: 100, waveEnemies: [
			{ enemyId: 'plane', spawnAmount: 50, spawnDelay: 10, spawnPos: 0 },
			{ enemyId: 'plane', spawnAmount: 20, spawnDelay: 60, spawnPos: 0 },
			{ enemyId: 'plane', spawnAmount: 24, spawnDelay: 30, spawnPos: 0 },
			{ enemyId: 'plane', spawnAmount: 30, spawnDelay: 40, spawnPos: 0 },
			{ enemyId: 'plane', spawnAmount: 5, spawnDelay: 50, spawnPos: 0 },
			{ enemyId: 'plane', spawnAmount: 30, spawnDelay: 20, spawnPos: 0 }
		]},
		{ postDelay: 120, reward: 100, waveEnemies: [
			{ enemyId: 'green-dude', spawnAmount: 50, spawnDelay: 15, spawnPos: 0 },
			{ enemyId: 'green-dude', spawnAmount: 40, spawnDelay: 10, spawnPos: 0 }
		]}
	],
	spritesheet: 'spritesheet',
	nodes: [
		{ type: 'start', x: 64, y: 64 },
		{ type: 'path', x: 64, y: 704 },
		{ type: 'path', x: 704, y: 704 },
		{ type: 'end', x: 704, y: 64 }
	],
	tiles:[
		[ 
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-l' },
			{ image: 'grass-l' },
			{ image: 'grass-l' },
			{ image: 'grass-l' },
			{ image: 'grass-l' },
			{ image: 'grass-l' },
			{ image: 'grass-l' },
			{ image: 'grass-c-bl' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-r' },
			{ image: 'grass-r' },
			{ image: 'grass-r' },
			{ image: 'grass-r' },
			{ image: 'grass-r' },
			{ image: 'grass-r' },
			{ image: 'grass-tr' },
			{ image: 'grass-b' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
		[ 
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' },
			{ image: 'grass-a' }
		],
	]
};
