export let levelData = {
	spritesheet: "spritesheet",
	tiles:[
		[ 
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-l" },
			{ image: "grass-l" },
			{ image: "grass-l" },
			{ image: "grass-l" },
			{ image: "grass-l" },
			{ image: "grass-l" },
			{ image: "grass-l" },
			{ image: "grass-c-bl" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-r" },
			{ image: "grass-r" },
			{ image: "grass-r" },
			{ image: "grass-r" },
			{ image: "grass-r" },
			{ image: "grass-r" },
			{ image: "grass-tr" },
			{ image: "grass-b" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
		[ 
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" },
			{ image: "grass-a" }
		],
	]
}
